#ifndef defs_H
#define defs_H

#define WINDOW_WIDTH 1020
#define WINDOW_HEIGHT 600

#define TILE_TYPE_WIDTH_NUMBER 12
#define TILE_TYPE_HEIGHT_NUMBER 24

#define TILE_MINER_WIDTH_NUMBER 6
#define TILE_MINER_HEIGHT_NUMBER 15

#define TILE_LEVEL_TYPE_NUMBER 6
#define TILE_SIZE 30

#define SPRITE_NUMBER 4

#define TILE_TYPE_NUMBER 14
#define MAX_KEYBOARD_KEY_NUMBER 350

#define FPS 30

#endif